services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules  # Evita que el volumen sobrescriba node_modules
    command: node server.js
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/headers:/etc/nginx/headers
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
